# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFlutterCompareiOSDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestFlutterCompareiOSDemo

  pod 'SDWebImage', '~> 4.4.2'
  pod 'MJRefresh', '~> 3.1.15.7'
end
